/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Connect.QLQuanCafe;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author quach
 */
public class Password extends javax.swing.JFrame {

    public static String ten;

    /**
     * Creates new form Password
     */
    public Password(String ten) {
        initComponents();
        this.ten = ten;
    }

    public void DoiMatKhau(String mkm) {
        Connection connect = QLQuanCafe.getConnectionToMSSQL();
        String sql = "update NGUOIDUNG set MATKHAU=? where TENND = ?";
        try {
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setString(1, mkm);
            ps.setString(2, ten);
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(Password.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public String LayMatKhau(String ten) {
        String pass = "";
        Connection connect = QLQuanCafe.getConnectionToMSSQL();
        String sql = "select MATKHAU from NGUOIDUNG where TENND = ?";
        try {
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setString(1, ten);
            ResultSet rs = ps.executeQuery();
            pass = rs.getString("MATKHAU");
        } catch (SQLException e) {
            Logger.getLogger(Password.class.getName()).log(Level.SEVERE, null, e);
        }
        return pass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpf_mkc = new javax.swing.JPasswordField();
        jpf_mkm = new javax.swing.JPasswordField();
        jpf_xnmkm = new javax.swing.JPasswordField();
        jb_doi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thay đổi mật khẩu");

        jLabel2.setText("Mật khẩu cũ");

        jb_doi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_doi.setText("Đổi");
        jb_doi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_doiActionPerformed(evt);
            }
        });

        jLabel3.setText("Mật khẩu mới");

        jLabel4.setText("Xác nhận mật khẩu mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jpf_mkc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf_mkm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jpf_xnmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jb_doi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf_mkc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf_mkm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf_xnmkm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addComponent(jb_doi)
                .addGap(248, 248, 248))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_doiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_doiActionPerformed
        // TODO add your handling code here:
        char[] mkc = jpf_mkc.getPassword();
        String mkcu;
        mkcu = new String(mkc);

        char[] mkm = jpf_mkm.getPassword();
        String mkmoi;
        mkmoi = new String(mkm);

        char[] xnmkm = jpf_xnmkm.getPassword();
        String xnmkmoi;
        xnmkmoi = new String(xnmkm);
        System.out.println(mkcu + " " + mkmoi);
        boolean ktramkc = true, ktramkm = true, ktraxnmkm = true;
        if (mkcu.equals("")) {
            ktramkc = false;
            JOptionPane.showMessageDialog(this, "Mat khau cu khong duoc de trong!");
        } else if (mkmoi.equals("")) {
            ktramkm = false;
            JOptionPane.showMessageDialog(this, "Mat khau moi khong duoc de trong!");
        } else if (mkcu.equals("")) {
            ktraxnmkm = false;
            JOptionPane.showMessageDialog(this, "Xac nhan mat khau moi khong duoc de trong!");
        } else if (!mkmoi.equals(xnmkmoi)) {
            ktraxnmkm = false;
            JOptionPane.showMessageDialog(this, "Hai mat khau phai giong nhau!");
        } else if (mkcu.equals(LayMatKhau(ten))) {
            ktramkc = false;
            JOptionPane.showMessageDialog(this, "Mat khau cu khong chinh xac!");
        } else if (ktramkc == true && ktramkm == true && ktraxnmkm == true) {
            DoiMatKhau(mkmoi);
            JOptionPane.showMessageDialog(this, "Thay doi mat khau thanh cong!");
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jb_doiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password(ten).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_doi;
    private javax.swing.JPasswordField jpf_mkc;
    private javax.swing.JPasswordField jpf_mkm;
    private javax.swing.JPasswordField jpf_xnmkm;
    // End of variables declaration//GEN-END:variables
}
