/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Connect.QLQuanCafe;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quach
 */
public class Pay extends javax.swing.JFrame {

    /**
     * Creates new form Pay
     */
    public Pay() {
        initComponents();
        String sql = "select * from HOADON where TRANGTHAI = 0";
        Connection ketNoi = QLQuanCafe.getConnectionToMSSQL();
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcb_mahd.addItem(rs.getString("MAHD"));
            }
        } catch (Exception e) {

        }
    }

    public void LayThongTinHoaDon(int mahd) {
        DefaultTableModel dtm = (DefaultTableModel) jt_hoadon.getModel();
        dtm.setNumRows(0);
        Connection ketNoi = QLQuanCafe.getConnectionToMSSQL();
        String sql = "select TENMON, SOLUONG, GIA from MON m, DATMON d, HOADON h where h.MAHD = ? and m.MAMON = d.MAMON and h.MABAN = d.MABAN";
        Vector vt;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, String.valueOf(mahd));
//            ps.executeUpdate();
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("TENMON"));
                vt.add(rs.getString("SOLUONG"));
                vt.add(rs.getString("GIA"));
                vt.add(Integer.parseInt(rs.getString("SOLUONG")) * Double.parseDouble(rs.getString("GIA")));
                dtm.addRow(vt);
            }
            jt_hoadon.setModel(dtm);
            rs.close();
            ps.close();
            ketNoi.close();
        } catch (SQLException e) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void ThanhToan(int mahd) {
        Connection ketNoi = QLQuanCafe.getConnectionToMSSQL();
        String sql = "update HOADON set TRANGTHAI = 1 where MAHD =?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, String.valueOf(mahd));
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql2 = "select MABAN from HOADON where MAHD = ?";
        int maban = 0;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql2);
            ps.setString(1, String.valueOf(mahd));
            ResultSet rs = ps.executeQuery();
            maban = Integer.parseInt(rs.getString("MABAN"));
        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql1 = "update BAN set TRANGTHAI = 1 where MABAN =?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql1);
            ps.setString(1, String.valueOf(maban));
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcb_mahd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_hoadon = new javax.swing.JTable();
        jb_thanhtoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Chọn thanh toán");

        jcb_mahd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_mahdMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcb_mahdMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcb_mahdMouseReleased(evt);
            }
        });
        jcb_mahd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcb_mahdKeyReleased(evt);
            }
        });

        jt_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên món", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(jt_hoadon);

        jb_thanhtoan.setText("Thanh toán");
        jb_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jcb_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                .addComponent(jb_thanhtoan)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_thanhtoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_mahdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_mahdMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jcb_mahdMouseClicked

    private void jcb_mahdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_mahdMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jcb_mahdMouseReleased

    private void jcb_mahdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_mahdKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jcb_mahdKeyReleased

    private void jcb_mahdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_mahdMouseExited
        // TODO add your handling code here:
        int mahd = Integer.parseInt(jcb_mahd.getSelectedItem().toString());
        LayThongTinHoaDon(mahd);
    }//GEN-LAST:event_jcb_mahdMouseExited

    private void jb_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thanhtoanActionPerformed
        // TODO add your handling code here:
        int mahd = Integer.parseInt(jcb_mahd.getSelectedItem().toString());

        int click = JOptionPane.showConfirmDialog(null, "Ban co chac muon thanh toan!");
        if (click == JOptionPane.YES_OPTION) {
            ThanhToan(mahd);
            JOptionPane.showMessageDialog(this, "Thanh toan thanh cong!");
            new Home("").setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Thanh toan khong thanh cong!");
        }

    }//GEN-LAST:event_jb_thanhtoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_thanhtoan;
    private javax.swing.JComboBox<String> jcb_mahd;
    private javax.swing.JTable jt_hoadon;
    // End of variables declaration//GEN-END:variables
}
